[
ToolSpec {
            name: "cargo_check",
            description: "运行 cargo check（结构化参数）。用于快速检查 Rust 项目编译问题。\n\n【cargo check 常用模式】检查整个项目：`cargo check`；检查特定包：`cargo check -p <package>`。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::CargoCommonCliArgs>,
            runner: ToolRunner::Typed(runner_cargo_check_try),
            summary: ToolSummaryKind::Static("cargo check"),
        },
        ToolSpec {
            name: "cargo_test",
            description: "运行 cargo test（支持 package/bin/filter/nocapture）。用于执行 Rust 测试。\n\n【cargo test 常用模式】运行所有测试：`cargo test`；运行特定测试：`cargo test <test_name>`；显示 println!：`cargo test -- --nocapture`；运行集成测试：`cargo test --test <integration_test_name>`。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::CargoTestArgs>,
            runner: ToolRunner::Typed(runner_cargo_test_try),
            summary: ToolSummaryKind::Static("cargo test"),
        },
        ToolSpec {
            name: "cargo_clippy",
            description: "运行 cargo clippy（结构化参数）。用于检查 Rust 代码潜在问题。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::CargoCommonCliArgs>,
            runner: ToolRunner::Typed(runner_cargo_clippy_try),
            summary: ToolSummaryKind::Static("cargo clippy"),
        },
        ToolSpec {
            name: "cargo_run",
            description: "运行 cargo run（结构化参数）。用于启动 Rust 可执行程序。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::CargoRunArgs>,
            runner: ToolRunner::Typed(runner_cargo_run_try),
            summary: ToolSummaryKind::Static("cargo run"),
        },
        ToolSpec {
            name: "cargo_nextest",
            description: "运行 cargo nextest run（需要已安装 cargo-nextest）。用于更快的测试执行。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::CargoNextestArgs>,
            runner: ToolRunner::Typed(runner_cargo_nextest_try),
            summary: ToolSummaryKind::Static("cargo nextest"),
        },
        ToolSpec {
            name: "cargo_fmt_check",
            description: "运行 cargo fmt --check（代码格式检查）。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::EmptyToolArgs>,
            runner: ToolRunner::Legacy(runner_cargo_fmt_check),
            summary: ToolSummaryKind::Static("cargo fmt --check"),
        },
        ToolSpec {
            name: "rust_compiler_json",
            description: "运行 `cargo check --message-format=<json>`，解析 **compiler-message** 行，输出结构化诊断摘要（级别、错误码、rendered、span）。等价于对接 rustc 的 JSON 诊断流，无需 rust-analyzer。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::RustCompilerJsonArgs>,
            runner: ToolRunner::Legacy(runner_rust_compiler_json),
            summary: ToolSummaryKind::Static("cargo check JSON diagnostics"),
        },
        ToolSpec {
            name: "rust_rustc",
            description: "在工作区根目录执行 **rustc**（不经 shell）。`args` 为参数数组，规则与 `run_command` 一致：不得含 `..` 或绝对路径。用于 `rustc --explain E0xxx`、`-vV`、`--print=cfg` 等；**不要求** Cargo.toml。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::RustRustcArgs>,
            runner: ToolRunner::Typed(runner_rust_rustc_try),
            summary: ToolSummaryKind::Static("rustc"),
        },
        ToolSpec {
            name: "rust_analyzer_goto_definition",
            description: "启动 **rust-analyzer**（stdio LSP），对指定 **path + 0-based line/character** 执行 `textDocument/definition`。需本机已安装 rust-analyzer；单文件 didOpen，适合跳转定义。大文件 >512KiB 请换 read_file 分段。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::RustAnalyzerPositionArgs>,
            runner: ToolRunner::Legacy(runner_rust_analyzer_goto_definition),
            summary: ToolSummaryKind::Dynamic(ts::summary_rust_analyzer_goto_definition),
        },
        ToolSpec {
            name: "rust_analyzer_find_references",
            description: "同上，执行 `textDocument/references`（语义引用）。参数含 include_declaration。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::RustAnalyzerReferencesArgs>,
            runner: ToolRunner::Legacy(runner_rust_analyzer_find_references),
            summary: ToolSummaryKind::Dynamic(ts::summary_rust_analyzer_find_references),
        },
        ToolSpec {
            name: "rust_analyzer_hover",
            description: "启动 **rust-analyzer**（stdio LSP），对 **path + 0-based line/character** 执行 `textDocument/hover`，输出悬停文档/类型等（Markdown 或纯文本）。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::RustAnalyzerPositionArgs>,
            runner: ToolRunner::Legacy(runner_rust_analyzer_hover),
            summary: ToolSummaryKind::Dynamic(ts::summary_rust_analyzer_hover),
        },
        ToolSpec {
            name: "rust_analyzer_document_symbol",
            description: "同上，对单文件执行 `textDocument/documentSymbol`：层级 `DocumentSymbol` 树或 `SymbolInformation` 列表，条数由 **max_symbols**（默认 500，上限 5000）截断。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::RustAnalyzerDocumentSymbolArgs>,
            runner: ToolRunner::Legacy(runner_rust_analyzer_document_symbol),
            summary: ToolSummaryKind::Dynamic(ts::summary_rust_analyzer_document_symbol),
        },
        ToolSpec {
            name: "rust_analyzer_goto_implementation",
            description: "同上，执行 `textDocument/implementation`（如 trait 方法跳转到 `impl`）。**path + 0-based line/character**；需 rust-analyzer。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::RustAnalyzerPositionArgs>,
            runner: ToolRunner::Legacy(runner_rust_analyzer_goto_implementation),
            summary: ToolSummaryKind::Dynamic(ts::summary_rust_analyzer_goto_implementation),
        },
        ToolSpec {
            name: "rust_analyzer_goto_type_definition",
            description: "同上，执行 `textDocument/typeDefinition`（解析到的类型定义位置）。**path + 0-based line/character**；需 rust-analyzer。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::RustAnalyzerPositionArgs>,
            runner: ToolRunner::Legacy(runner_rust_analyzer_goto_type_definition),
            summary: ToolSummaryKind::Dynamic(ts::summary_rust_analyzer_goto_type_definition),
        },
        ToolSpec {
            name: "rust_analyzer_document_highlight",
            description: "同上，执行 `textDocument/documentHighlight`（当前位置符号在文件内的读/写/Text 高亮区间）。**path + 0-based line/character**；需 rust-analyzer。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::RustAnalyzerPositionArgs>,
            runner: ToolRunner::Legacy(runner_rust_analyzer_document_highlight),
            summary: ToolSummaryKind::Dynamic(ts::summary_rust_analyzer_document_highlight),
        },
        ToolSpec {
            name: "rust_analyzer_workspace_symbol",
            description: "同上，执行 `workspace/symbol` 按 **query** 模糊搜索工作区符号。仍须 **path** 指向一 Rust 源以 `didOpen`（与现有会话一致）；**max_results** 默认 64、上限 500。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::RustAnalyzerWorkspaceSymbolArgs>,
            runner: ToolRunner::Legacy(runner_rust_analyzer_workspace_symbol),
            summary: ToolSummaryKind::Dynamic(ts::summary_rust_analyzer_workspace_symbol),
        },
        ToolSpec {
            name: "rust_test_one",
            description: "运行单个 Rust 测试（按 test_name 过滤）。用于快速调试具体测试。",
            category: ToolCategory::Development,
            parameters: schema_of::<args::RustTestOneArgs>,
            runner: ToolRunner::Typed(runner_rust_test_one_try),
            summary: ToolSummaryKind::Static("single Rust test"),
        },
]
