[
// ── Git 写操作补全 ──────────────────────────────────
        ToolSpec {
            name: "git_checkout",
            description: "切换分支、标签或恢复文件（受控写入）。参数 target 为分支名/标签名/commit SHA；create=true 时以 -b 创建新分支。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_checkout,
            runner: runner_git_checkout,
            summary: ToolSummaryKind::Dynamic(ts::summary_git_checkout),
        },
        ToolSpec {
            name: "git_branch_create",
            description: "创建新分支（不切换）。参数 name 为分支名，可选 start_point 为起始点。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_branch_create,
            runner: runner_git_branch_create,
            summary: ToolSummaryKind::Dynamic(ts::summary_git_branch_create),
        },
        ToolSpec {
            name: "git_branch_delete",
            description: "删除本地分支（受控写入，需 confirm=true）。默认 -d（需已合并）；force=true 时 -D 强制删除。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_branch_delete,
            runner: runner_git_branch_delete,
            summary: ToolSummaryKind::Dynamic(ts::summary_git_branch_delete),
        },
        ToolSpec {
            name: "git_push",
            description: "推送到远程仓库（受控写入，需 confirm=true）。默认 remote=origin；可选 set_upstream、force_with_lease、tags。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_push,
            runner: runner_git_push,
            summary: ToolSummaryKind::Dynamic(ts::summary_git_push),
        },
        ToolSpec {
            name: "git_merge",
            description: "合并指定分支到当前分支（受控写入，需 confirm=true）。可选 no_ff、squash、message。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_merge,
            runner: runner_git_merge,
            summary: ToolSummaryKind::Dynamic(ts::summary_git_merge),
        },
        ToolSpec {
            name: "git_rebase",
            description: "将当前分支变基到指定目标（受控写入，需 confirm=true）。onto 为目标分支/SHA；支持 abort/continue 操作冲突。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_rebase,
            runner: runner_git_rebase,
            summary: ToolSummaryKind::Dynamic(ts::summary_git_rebase),
        },
        ToolSpec {
            name: "git_stash",
            description: "Git 暂存管理：action=push（暂存，可带 message）/pop（恢复并删除）/apply（恢复不删除）/list/drop/clear（需 confirm）。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_stash,
            runner: runner_git_stash,
            summary: ToolSummaryKind::Dynamic(ts::summary_git_stash),
        },
        ToolSpec {
            name: "git_tag",
            description: "Git 标签管理：action=list（列出标签，可按 pattern 过滤）/create（创建标签，可加 message 成为注释标签）/delete（删除标签，需 confirm）。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_tag,
            runner: runner_git_tag,
            summary: ToolSummaryKind::Dynamic(ts::summary_git_tag),
        },
        ToolSpec {
            name: "git_reset",
            description: "重置 HEAD 到指定位置（受控写入，需 confirm=true）。mode=soft/mixed（默认）/hard；target 默认 HEAD。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_reset,
            runner: runner_git_reset,
            summary: ToolSummaryKind::Dynamic(ts::summary_git_reset),
        },
        ToolSpec {
            name: "git_cherry_pick",
            description: "将指定 commit 应用到当前分支（受控写入，需 confirm=true）。支持单个 commit 或 commits 数组；可 no_commit 仅暂存；支持 abort/continue。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_cherry_pick,
            runner: runner_git_cherry_pick,
            summary: ToolSummaryKind::Static("git cherry-pick"),
        },
        ToolSpec {
            name: "git_revert",
            description: "回滚指定 commit（受控写入，需 confirm=true）。创建一个反向提交；可 no_commit 仅暂存不提交；支持 abort/continue。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_revert,
            runner: runner_git_revert,
            summary: ToolSummaryKind::Dynamic(ts::summary_git_revert),
        },
        // ── Node.js / npm / npx ─────────────────────────────
]
