#!/bin/sh
set -e

case "$1" in
configure)
	if ! getent group crabmate >/dev/null; then
		addgroup --system crabmate
	fi
	if ! getent passwd crabmate >/dev/null; then
		adduser --system --ingroup crabmate --home /var/lib/crabmate \
			--shell /usr/sbin/nologin --gecos "CrabMate" crabmate
	fi
	mkdir -p /var/lib/crabmate
	chown crabmate:crabmate /var/lib/crabmate
	;;
esac

#DEBHELPER#

exit 0
