fn build_agent_config_from_finalize(
    mid: FinalizeAfterRoles,
    tail: FinalizeTailScalars,
) -> AgentConfig {
    let FinalizeAfterRoles {
        b,
        tr,
        ltm,
        sem,
        intent,
        max_message_history,
        tui_load_session_on_start,
        tui_session_max_messages,
        repl_initial_workspace_messages_enabled,
        command_timeout_secs,
        command_max_output_len,
        max_tokens,
        llm_context_tokens,
        temperature,
        api_timeout_secs,
        api_max_retries,
        api_retry_delay_secs,
        weather_timeout_secs,
        reflection_default_max_rounds,
        allowed_commands,
        workspace_allowed_roots,
        system_prompt,
        default_agent_role_id,
        agent_roles,
        run_command_working_dir,
        ..
    } = mid;

    let FinalizeTailScalars {
        cursor_rules_enabled,
        cursor_rules_dir,
        cursor_rules_include_agents_md,
        cursor_rules_max_chars,
        skills_enabled,
        skills_dir,
        skills_max_chars,
        skills_top_k,
        final_plan_requirement,
        plan_rewrite_max_attempts,
        final_plan_require_strict_workflow_node_coverage,
        final_plan_semantic_check_enabled,
        final_plan_semantic_check_max_non_readonly_tools,
        final_plan_semantic_check_max_tokens,
        planner_executor_mode,
        tool_message_max_chars,
        tool_result_envelope_v1,
        sse_tool_call_include_arguments,
        agent_thinking_trace_enabled,
        agent_tool_stats_enabled,
        agent_tool_stats_window_events,
        agent_tool_stats_min_samples,
        agent_tool_stats_max_chars,
        agent_tool_stats_warn_below_success_ratio,
        materialize_deepseek_dsml_tool_calls,
        thinking_avoid_echo_system_prompt,
        thinking_avoid_echo_appendix,
        context_char_budget,
        context_min_messages_after_system,
        context_summary_trigger_chars,
        context_summary_tail_messages,
        context_summary_max_tokens,
        context_summary_transcript_max_chars,
        health_llm_models_probe,
        health_llm_models_probe_cache_secs,
        chat_queue_max_concurrent,
        chat_queue_max_pending,
        parallel_readonly_tools_max,
        read_file_turn_cache_max_entries,
        test_result_cache_enabled,
        test_result_cache_max_entries,
        session_workspace_changelist_enabled,
        session_workspace_changelist_max_chars,
        staged_plan_execution,
        staged_plan_phase_instruction,
        staged_plan_allow_no_task,
        staged_plan_feedback_mode,
        staged_plan_patch_max_attempts,
        staged_plan_cli_show_planner_stream,
        staged_plan_optimizer_round,
        staged_plan_optimizer_requires_parallel_tools,
        staged_plan_ensemble_count,
        staged_plan_skip_ensemble_on_casual_prompt,
        staged_plan_two_phase_nl_display,
        sync_default_tool_sandbox_mode,
        sync_default_tool_sandbox_docker_image,
        sync_default_tool_sandbox_docker_network,
        sync_default_tool_sandbox_docker_timeout_secs,
        sync_default_tool_sandbox_docker_user,
        web_api_bearer_token,
        web_api_require_bearer,
        web_audit_log_write_tools,
        web_audit_trust_x_forwarded_for,
        allow_insecure_no_auth_for_non_loopback,
        conversation_store_sqlite_path,
        agent_memory_file_enabled,
        agent_memory_file,
        agent_memory_file_max_chars,
        living_docs_inject_enabled,
        living_docs_relative_dir,
        living_docs_inject_max_chars,
        living_docs_file_max_each_chars,
        project_profile_inject_enabled,
        project_profile_inject_max_chars,
        project_dependency_brief_inject_enabled,
        project_dependency_brief_inject_max_chars,
        tool_call_explain_enabled,
        tool_call_explain_min_chars,
        tool_call_explain_max_chars,
        mcp_enabled,
        mcp_command,
        mcp_tool_timeout_secs,
        web_search_provider,
        web_search_api_key,
        web_search_timeout_secs,
        web_search_max_results,
        http_fetch_allowed_prefixes,
        http_fetch_timeout_secs,
        http_fetch_max_response_bytes,
        scheduled_agent_tasks,
    } = tail;

    AgentConfig {
        api_base: b.api_base.clone(),
        model: b.model.clone(),
        planner_model: b.planner_model.clone(),
        executor_model: b.executor_model.clone(),
        llm_http_auth_mode: intent.llm_http_auth_mode,
        max_message_history,
        tui_load_session_on_start,
        tui_session_max_messages,
        repl_initial_workspace_messages_enabled,
        command_timeout_secs,
        command_max_output_len,
        allowed_commands,
        run_command_working_dir: run_command_working_dir.display().to_string(),
        max_tokens,
        llm_context_tokens,
        temperature,
        llm_seed: b.llm_seed,
        llm_reasoning_split: intent.llm_reasoning_split,
        llm_bigmodel_thinking: b.llm_bigmodel_thinking.unwrap_or(false),
        llm_kimi_thinking_disabled: b.llm_kimi_thinking_disabled.unwrap_or(false),
        api_timeout_secs,
        api_max_retries,
        api_retry_delay_secs,
        weather_timeout_secs,
        web_search_provider,
        web_search_api_key,
        web_search_timeout_secs,
        web_search_max_results,
        http_fetch_allowed_prefixes,
        http_fetch_timeout_secs,
        http_fetch_max_response_bytes,
        reflection_default_max_rounds,
        final_plan_requirement,
        plan_rewrite_max_attempts,
        final_plan_require_strict_workflow_node_coverage,
        final_plan_semantic_check_enabled,
        final_plan_semantic_check_max_non_readonly_tools,
        final_plan_semantic_check_max_tokens,
        planner_executor_mode,
        system_prompt,
        default_agent_role_id,
        agent_roles,
        cursor_rules_enabled,
        cursor_rules_dir,
        cursor_rules_include_agents_md,
        cursor_rules_max_chars: cursor_rules_max_chars as usize,
        skills_enabled,
        skills_dir,
        skills_max_chars: skills_max_chars as usize,
        skills_top_k,
        tool_message_max_chars,
        tool_result_envelope_v1,
        sse_tool_call_include_arguments,
        agent_thinking_trace_enabled,
        agent_tool_stats_enabled,
        agent_tool_stats_window_events,
        agent_tool_stats_min_samples,
        agent_tool_stats_max_chars,
        agent_tool_stats_warn_below_success_ratio,
        materialize_deepseek_dsml_tool_calls,
        thinking_avoid_echo_system_prompt,
        thinking_avoid_echo_appendix,
        context_char_budget,
        context_min_messages_after_system,
        context_summary_trigger_chars,
        context_summary_tail_messages,
        context_summary_max_tokens,
        context_summary_transcript_max_chars,
        workspace_allowed_roots,
        web_api_bearer_token,
        web_api_require_bearer,
        web_audit_log_write_tools,
        web_audit_trust_x_forwarded_for,
        allow_insecure_no_auth_for_non_loopback,
        health_llm_models_probe,
        health_llm_models_probe_cache_secs,
        chat_queue_max_concurrent,
        chat_queue_max_pending,
        parallel_readonly_tools_max,
        read_file_turn_cache_max_entries,
        test_result_cache_enabled,
        test_result_cache_max_entries,
        session_workspace_changelist_enabled,
        session_workspace_changelist_max_chars,
        staged_plan_execution,
        staged_plan_phase_instruction,
        staged_plan_allow_no_task,
        staged_plan_feedback_mode,
        staged_plan_patch_max_attempts,
        staged_plan_cli_show_planner_stream,
        staged_plan_optimizer_round,
        staged_plan_optimizer_requires_parallel_tools,
        staged_plan_ensemble_count,
        staged_plan_skip_ensemble_on_casual_prompt,
        staged_plan_two_phase_nl_display,
        sync_default_tool_sandbox_mode,
        sync_default_tool_sandbox_docker_image,
        sync_default_tool_sandbox_docker_network,
        sync_default_tool_sandbox_docker_timeout_secs,
        sync_default_tool_sandbox_docker_user,
        conversation_store_sqlite_path,
        scheduled_agent_tasks,
        agent_memory_file_enabled,
        agent_memory_file,
        agent_memory_file_max_chars,
        living_docs_inject_enabled,
        living_docs_relative_dir,
        living_docs_inject_max_chars,
        living_docs_file_max_each_chars,
        project_profile_inject_enabled,
        project_profile_inject_max_chars,
        project_dependency_brief_inject_enabled,
        project_dependency_brief_inject_max_chars,
        tool_call_explain_enabled,
        tool_call_explain_min_chars,
        tool_call_explain_max_chars,
        long_term_memory_enabled: ltm.long_term_memory_enabled,
        long_term_memory_scope_mode: ltm.long_term_memory_scope_mode,
        long_term_memory_vector_backend: ltm.long_term_memory_vector_backend,
        long_term_memory_max_entries: ltm.long_term_memory_max_entries,
        long_term_memory_inject_max_chars: ltm.long_term_memory_inject_max_chars,
        long_term_memory_store_sqlite_path: ltm.long_term_memory_store_sqlite_path,
        long_term_memory_top_k: ltm.long_term_memory_top_k,
        long_term_memory_max_chars_per_chunk: ltm.long_term_memory_max_chars_per_chunk,
        long_term_memory_min_chars_to_index: ltm.long_term_memory_min_chars_to_index,
        long_term_memory_async_index: ltm.long_term_memory_async_index,
        long_term_memory_auto_index_turns: ltm.long_term_memory_auto_index_turns,
        long_term_memory_default_ttl_secs: ltm.long_term_memory_default_ttl_secs,
        mcp_enabled,
        mcp_command,
        mcp_tool_timeout_secs,
        codebase_semantic_search_enabled: sem.codebase_semantic_search_enabled,
        codebase_semantic_invalidate_on_workspace_change: sem
            .codebase_semantic_invalidate_on_workspace_change,
        codebase_semantic_index_sqlite_path: sem.codebase_semantic_index_sqlite_path.clone(),
        codebase_semantic_max_file_bytes: sem.codebase_semantic_max_file_bytes,
        codebase_semantic_chunk_max_chars: sem.codebase_semantic_chunk_max_chars,
        codebase_semantic_top_k: sem.codebase_semantic_top_k,
        codebase_semantic_query_max_chunks: sem.codebase_semantic_query_max_chunks,
        codebase_semantic_rebuild_max_files: sem.codebase_semantic_rebuild_max_files,
        codebase_semantic_rebuild_incremental: sem.codebase_semantic_rebuild_incremental,
        codebase_semantic_hybrid_alpha: sem.codebase_semantic_hybrid_alpha,
        codebase_semantic_fts_top_n: sem.codebase_semantic_fts_top_n,
        codebase_semantic_hybrid_semantic_pool: sem.codebase_semantic_hybrid_semantic_pool,
        tool_registry_http_fetch_wall_timeout_secs: tr.tool_registry_http_fetch_wall_timeout_secs,
        tool_registry_http_request_wall_timeout_secs: tr
            .tool_registry_http_request_wall_timeout_secs,
        tool_registry_parallel_wall_timeout_secs: tr.tool_registry_parallel_wall_timeout_secs,
        tool_registry_parallel_sync_denied_tools: tr.tool_registry_parallel_sync_denied_tools,
        tool_registry_parallel_sync_denied_prefixes: tr.tool_registry_parallel_sync_denied_prefixes,
        tool_registry_sync_default_inline_tools: tr.tool_registry_sync_default_inline_tools,
        tool_registry_write_effect_tools: tr.tool_registry_write_effect_tools,
        tool_registry_sub_agent_patch_write_extra_tools: tr
            .tool_registry_sub_agent_patch_write_extra_tools,
        tool_registry_sub_agent_test_runner_extra_tools: tr
            .tool_registry_sub_agent_test_runner_extra_tools,
        tool_registry_sub_agent_review_readonly_deny_tools: tr
            .tool_registry_sub_agent_review_readonly_deny_tools,
        max_turn_duration_seconds: 600,
        max_turn_tokens: 100_000,
        full_plan_rewrite_max_attempts: 2,
        enable_llm_routing: Some(true), // 默认开启 LLM 智能路由
        intent_mode_bias_enabled: intent.intent_mode_bias_enabled,
        intent_l2_enabled: intent.intent_l2_enabled,
        intent_l2_min_confidence: intent.intent_l2_min_confidence,
        intent_l2_max_tokens: intent.intent_l2_max_tokens,
        intent_execute_low_threshold: intent.intent_execute_low_threshold,
        intent_execute_high_threshold: intent.intent_execute_high_threshold,
        intent_non_hier_execute_low_threshold: intent.intent_non_hier_execute_low_threshold,
        intent_non_hier_execute_high_threshold: intent.intent_non_hier_execute_high_threshold,
        intent_at_turn_start_enabled: intent.intent_at_turn_start_enabled,
        intent_l0_routing_boost_enabled: intent.intent_l0_routing_boost_enabled,
    }
}

fn finalize_agent_config_tail(mid: FinalizeAfterRoles) -> Result<AgentConfig, String> {
    let tail = derive_finalize_tail_scalars(&mid)?;
    Ok(build_agent_config_from_finalize(mid, tail))
}

pub(super) fn finalize(
    b: ConfigBuilder,
    system_prompt_search_bases: Vec<PathBuf>,
) -> Result<AgentConfig, String> {
    finalize_agent_config(b, system_prompt_search_bases)
}
