#!/usr/bin/env bash
# 将分散的 CSS 合并为单文件，减少桌面 WebView 首屏 HTTP 往返。
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
frontend="${root}/frontend"
out="${frontend}/styles/app.bundle.css"

parts=(
  "styles/tokens.css"
  "styles/fonts-local.css"
  "themes/light.css"
  "themes/material.css"
  "themes/high-contrast.css"
  "styles/base.css"
  "styles/components.css"
  "styles/layout-chat.css"
  "styles/shell-topbar.css"
  "styles/ide-layout.css"
  "styles/ide-codemirror.css"
  "styles/ide-highlight.css"
  "styles/shell-ds.css"
  "styles/tauri-shell.css"
  "styles/sidebar.css"
  "styles/status.css"
  "styles/approval.css"
  "styles/modal.css"
  "styles/motion.css"
)

{
  echo "/* CrabMate app.bundle.css — generated by scripts/bundle-frontend-css.sh; do not edit */"
  for rel in "${parts[@]}"; do
    path="${frontend}/${rel}"
    if [[ ! -f "${path}" ]]; then
      echo "error: missing ${path}" >&2
      exit 1
    fi
    echo ""
    echo "/* ===== ${rel} ===== */"
    cat "${path}"
  done
} > "${out}"

echo "bundled frontend CSS -> ${out}"
