[
        ToolSpec {
            name: "present_clarification_questionnaire",
            description: "向 Web 客户端下发**澄清问卷**控制面（SSE `clarification_questionnaire`）：当信息不足需用户逐项回答时调用。须提供稳定 `questionnaire_id` 与 1～12 道题目（`id`/`label`/可选 `hint`/`required`/`kind`）。**仅 Web 流式**会弹出问卷 UI；CLI/TUI 仍收到工具正文。用户下一条 `POST /chat` 或 `/chat/stream` 须在 JSON 中带 `clarify_questionnaire_answers`（与 `questionnaire_id` 及题目 `id` 对齐）。**禁止**在 `intro`/`label` 中要求用户粘贴密钥或隐私原文。",
            category: ToolCategory::Development,
            parameters: tool_params::params_present_clarification_questionnaire,
            runner: runner_present_clarification_questionnaire,
            summary: ToolSummaryKind::Static("Present clarification questionnaire (Web SSE)"),
        },
        ToolSpec {
            name: "diagnostic_summary",
            description: "只读排障摘要：**Rust 工具链**（rustc/cargo -V、rustc -vV 的 host/release、rustup default、bc 是否可用）、**工作区**（根路径、`target/` 是否存在、`Cargo.toml` / `frontend-leptos/Trunk.toml` / `frontend-leptos/dist` 是否存在）、**环境变量仅状态**（`API_KEY`、常见 `AGENT_*`、`RUST_LOG` 等：未设置/空/非空；**永不输出变量值**；密钥类亦不输出长度）。可选 `extra_env_vars`（大写安全名）。与 AGENTS.md 排障场景一致。",
            category: ToolCategory::Development,
            parameters: tool_params::params_diagnostic_summary,
            runner: runner_diagnostic_summary,
            summary: ToolSummaryKind::Static("Environment/toolchain diagnostic summary (redacted)"),
        },
        ToolSpec {
            name: "error_output_playbook",
            description: "只读：对**已脱敏**的 rustc/cargo/npm/pytest 等错误输出做启发式**归类**（依赖/网络/权限/磁盘/语法与类型/测试等），并给出 **2～3 条**可经 **`run_command`** 执行的排查命令**建议字符串**（**不执行**；仅包含当前 `allowed_commands` 白名单内的命令）。可选 `ecosystem`：`auto`（默认）/ `rust` / `node` / `python` / `generic`；可选 `max_chars` 限制输入长度。内置轻度掩码常见 `API_KEY=` 样式；**粘贴前仍须人工脱敏**。",
            category: ToolCategory::Development,
            parameters: tool_params::params_error_output_playbook,
            runner: runner_error_output_playbook,
            summary: ToolSummaryKind::Dynamic(ts::summary_error_output_playbook),
        },
        ToolSpec {
            name: "playbook_run_commands",
            description: "与 **`error_output_playbook`** 相同的启发式归类后，**依次**将 **1～3 条**建议命令经 **`run_command`** 在工作区**真实执行**（白名单、参数安全规则与 `run_command` 一致；可能触发 cargo/npm 等构建锁）。参数同 `error_output_playbook`，另可选 **`max_commands`**（默认 3）。**须可信工作区**；错误文本请先脱敏。",
            category: ToolCategory::Development,
            parameters: tool_params::params_playbook_run_commands,
            runner: runner_playbook_run_commands,
            summary: ToolSummaryKind::Static("Run error playbook suggestions via run_command"),
        },
        ToolSpec {
            name: "changelog_draft",
            description: "根据 **git log** 生成 **Markdown 变更说明草稿**（**不写仓库**）。支持按提交日聚合 subject、`flat` 平铺、或 `tag_ranges` 按 semver 降序相邻 tag 分段（`--no-merges`）。可选 since/until 与 max_commits。",
            category: ToolCategory::Development,
            parameters: tool_params::params_changelog_draft,
            runner: runner_changelog_draft,
            summary: ToolSummaryKind::Static("Generate changelog Markdown draft"),
        },
        ToolSpec {
            name: "license_notice",
            description: "运行 **cargo metadata** 解析依赖图，生成 **crate → license** 的 Markdown 表（**只读**；未在 Cargo.toml 声明的显示占位说明）。可选仅工作区成员、限制行数。非法律意见，发版前需人工核对。",
            category: ToolCategory::Development,
            parameters: tool_params::params_license_notice,
            runner: runner_license_notice,
            summary: ToolSummaryKind::Static("Dependency license summary (cargo metadata)"),
        },
        ToolSpec {
            name: "repo_overview_sweep",
            description: "只读聚合：可选**项目画像**（与 Web `GET /workspace/profile` 及首轮注入同源：清单与 tokei 等，默认开启，见 `include_project_profile` / `project_profile_max_chars`）；依次预览主要文档（默认 README/AGENTS/docs 等）、对源码根目录做 list_tree、用 glob 汇总 Cargo.toml/package.json/CI 等构建清单路径；末尾附**结论撰写提纲**。**分析结论由模型根据输出撰写**，本工具不调用 LLM。",
            category: ToolCategory::Development,
            parameters: tool_params::params_repo_overview_sweep,
            runner: runner_repo_overview_sweep,
            summary: ToolSummaryKind::Static("repo docs + tree + build files sweep"),
        },
        ToolSpec {
            name: "long_term_remember",
            description: "将短文本**显式**写入本会话长期记忆（SQLite，与自动回合索引分源）；可选 `tags` 与 `ttl_secs`（0=不过期）。须启用 `long_term_memory_enabled` 且本会话已挂载记忆库。勿写入密钥或隐私原文。",
            category: ToolCategory::Development,
            parameters: tool_params::params_long_term_remember,
            runner: runner_long_term_remember,
            summary: ToolSummaryKind::Static("Explicit long-term memory write"),
        },
        ToolSpec {
            name: "long_term_forget",
            description: "按 `memory_id` 或正文精确匹配删除长期记忆条目；可选 `explicit_only` 仅删显式记忆。",
            category: ToolCategory::Development,
            parameters: tool_params::params_long_term_forget,
            runner: runner_long_term_forget,
            summary: ToolSummaryKind::Static("Delete long-term memory entry"),
        },
        ToolSpec {
            name: "long_term_memory_list",
            description: "列出本会话最近若干条未过期记忆（含 id、来源、过期时间与标签摘要）。",
            category: ToolCategory::Development,
            parameters: tool_params::params_long_term_memory_list,
            runner: runner_long_term_memory_list,
            summary: ToolSummaryKind::Static("List recent long-term memory rows"),
        },
]
