[
        ToolSpec {
            name: "diagnostic_summary",
            description: "只读排障摘要：**Rust 工具链**（rustc/cargo -V、rustc -vV 的 host/release、rustup default、bc 是否可用）、**工作区**（根路径、`target/` 是否存在、`Cargo.toml` / `frontend/package.json` / `frontend/dist` 是否存在）、**环境变量仅状态**（`API_KEY`、常见 `AGENT_*`、`RUST_LOG` 等：未设置/空/非空；**永不输出变量值**；密钥类亦不输出长度）。可选 `extra_env_vars`（大写安全名）。与 AGENTS.md 排障场景一致。",
            category: ToolCategory::Development,
            parameters: tool_params::params_diagnostic_summary,
            runner: runner_diagnostic_summary,
            summary: ToolSummaryKind::Static("Environment/toolchain diagnostic summary (redacted)"),
        },
        ToolSpec {
            name: "error_output_playbook",
            description: "只读：对**已脱敏**的 rustc/cargo/npm/pytest 等错误输出做启发式**归类**（依赖/网络/权限/磁盘/语法与类型/测试等），并给出 **2～3 条**可经 **`run_command`** 执行的排查命令**建议字符串**（**不执行**；仅包含当前 `allowed_commands` 白名单内的命令）。可选 `ecosystem`：`auto`（默认）/ `rust` / `node` / `python` / `generic`；可选 `max_chars` 限制输入长度。内置轻度掩码常见 `API_KEY=` 样式；**粘贴前仍须人工脱敏**。",
            category: ToolCategory::Development,
            parameters: tool_params::params_error_output_playbook,
            runner: runner_error_output_playbook,
            summary: ToolSummaryKind::Dynamic(ts::summary_error_output_playbook),
        },
        ToolSpec {
            name: "changelog_draft",
            description: "根据 **git log** 生成 **Markdown 变更说明草稿**（**不写仓库**）。支持按提交日聚合 subject、`flat` 平铺、或 `tag_ranges` 按 semver 降序相邻 tag 分段（`--no-merges`）。可选 since/until 与 max_commits。",
            category: ToolCategory::Development,
            parameters: tool_params::params_changelog_draft,
            runner: runner_changelog_draft,
            summary: ToolSummaryKind::Static("Generate changelog Markdown draft"),
        },
        ToolSpec {
            name: "license_notice",
            description: "运行 **cargo metadata** 解析依赖图，生成 **crate → license** 的 Markdown 表（**只读**；未在 Cargo.toml 声明的显示占位说明）。可选仅工作区成员、限制行数。非法律意见，发版前需人工核对。",
            category: ToolCategory::Development,
            parameters: tool_params::params_license_notice,
            runner: runner_license_notice,
            summary: ToolSummaryKind::Static("Dependency license summary (cargo metadata)"),
        },
        ToolSpec {
            name: "repo_overview_sweep",
            description: "只读聚合：依次预览主要文档（默认 README/AGENTS/docs 等）、对源码根目录做 list_tree、用 glob 汇总 Cargo.toml/package.json/CI 等构建清单路径；末尾附**结论撰写提纲**。**分析结论由模型根据输出撰写**，本工具不调用 LLM。",
            category: ToolCategory::Development,
            parameters: tool_params::params_repo_overview_sweep,
            runner: runner_repo_overview_sweep,
            summary: ToolSummaryKind::Static("repo docs + tree + build files sweep"),
        },
]
