[
ToolSpec {
            name: "create_file",
            description: "在工作区内创建新文件。仅当文件不存在时创建；若路径已存在则报错。路径相对于工作目录，不能包含 .. 超出工作目录。用于用户要求「新建文件」「创建 xx」等。参数 path 为相对路径，content 为文件内容。",
            category: ToolCategory::Development,
            parameters: tool_params::params_file_write,
            runner: runner_create_file,
            summary: ToolSummaryKind::Dynamic(ts::summary_create_file),
        },
        ToolSpec {
            name: "modify_file",
            description: "在工作区内修改已有文件。mode=full（默认）：整文件覆盖。mode=replace_lines：仅替换 start_line..=end_line 为 content，流式读写不写全文件进内存，适合大文件局部修改。",
            category: ToolCategory::Development,
            parameters: tool_params::params_modify_file,
            runner: runner_modify_file,
            summary: ToolSummaryKind::Dynamic(ts::summary_modify_file),
        },
        ToolSpec {
            name: "copy_file",
            description: "在工作区内复制**文件**（非目录）。路径校验与 create/read 一致（禁止绝对路径与 `..` 越界、借助 symlink 逃逸）。目标为已存在文件时须 `overwrite=true` 才覆盖；目标为已存在目录会报错。适合批量整理而无需把内容读进对话。",
            category: ToolCategory::Development,
            parameters: tool_params::params_file_from_to_overwrite,
            runner: runner_copy_file,
            summary: ToolSummaryKind::Dynamic(ts::summary_copy_file),
        },
        ToolSpec {
            name: "move_file",
            description: "在工作区内移动/重命名**文件**。`overwrite` 语义同 `copy_file`。跨文件系统时 `rename` 失败会自动回退为复制后删除源文件。",
            category: ToolCategory::Development,
            parameters: tool_params::params_file_from_to_overwrite,
            runner: runner_move_file,
            summary: ToolSummaryKind::Dynamic(ts::summary_move_file),
        },
        ToolSpec {
            name: "read_file",
            description: "按行流式读取文件（不把整文件载入内存）。默认单次最多返回 max_lines=500 行（可调到 8000）；未指定 end_line 时自动分段。输出提示下一段 start_line。可选 count_total_lines 统计总行数（大文件慎用）。",
            category: ToolCategory::Development,
            parameters: tool_params::params_read_file,
            runner: runner_read_file,
            summary: ToolSummaryKind::Dynamic(ts::summary_read_file),
        },
        ToolSpec {
            name: "read_dir",
            description: "在工作区内读取目录下的文件/子目录列表（受控只读）。可选包含隐藏项、最大条数、文件大小（include_size）、修改时间（include_mtime）和排序方式（sort_by: name/size/mtime）。",
            category: ToolCategory::Development,
            parameters: tool_params::params_read_dir_enhanced,
            runner: runner_read_dir,
            summary: ToolSummaryKind::Dynamic(ts::summary_read_dir),
        },
        ToolSpec {
            name: "glob_files",
            description: "在工作区内从指定子目录起递归扫描，按 glob 模式匹配**文件**相对路径（如 **/*.rs）。带 max_depth、max_results 上限；路径均在工作区内解析，禁止 ..。优先于 run_command find。",
            category: ToolCategory::Development,
            parameters: tool_params::params_glob_files,
            runner: runner_glob_files,
            summary: ToolSummaryKind::Dynamic(ts::summary_glob_files),
        },
        ToolSpec {
            name: "list_tree",
            description: "在工作区内从指定目录起递归列出子路径（先序、字典序），前缀 dir:/file:；带 max_depth、max_entries。用于快速看目录树而不用 find。",
            category: ToolCategory::Development,
            parameters: tool_params::params_list_tree,
            runner: runner_list_tree,
            summary: ToolSummaryKind::Dynamic(ts::summary_list_tree),
        },
        ToolSpec {
            name: "file_exists",
            description: "检查工作区内某路径（文件或目录）是否存在，并可按 kind=file|dir|any 过滤。",
            category: ToolCategory::Development,
            parameters: tool_params::params_file_exists,
            runner: runner_file_exists,
            summary: ToolSummaryKind::Dynamic(ts::summary_file_exists),
        },
        ToolSpec {
            name: "read_binary_meta",
            description: "读取任意文件的元数据（大小、可选修改时间）及**文件头一段的 SHA256**，不把整文件读入上下文；适合二进制/大文件比对。prefix_hash_bytes 默认 8192，0 表示跳过哈希。",
            category: ToolCategory::Development,
            parameters: tool_params::params_read_binary_meta,
            runner: runner_read_binary_meta,
            summary: ToolSummaryKind::Dynamic(ts::summary_read_binary_meta),
        },
        ToolSpec {
            name: "hash_file",
            description: "对工作区内**常规文件**做只读哈希（流式读取，不占满内存）：**sha256**（默认）、**sha512**、**blake3**。可选 `max_bytes` 仅哈希前缀（用于大文件抽样或对齐外部工具）；路径解析与 `read_file` 相同。",
            category: ToolCategory::Development,
            parameters: tool_params::params_hash_file,
            runner: runner_hash_file,
            summary: ToolSummaryKind::Dynamic(ts::summary_hash_file),
        },
        ToolSpec {
            name: "extract_in_file",
            description: "在指定文件内按正则抽取匹配行（只读）。返回带行号的匹配行，并支持截断。",
            category: ToolCategory::Development,
            parameters: tool_params::params_extract_in_file,
            runner: runner_extract_in_file,
            summary: ToolSummaryKind::Dynamic(ts::summary_extract_in_file),
        },
        ToolSpec {
            name: "apply_patch",
            description: "应用 **unified diff**。路径：--- src/…（strip=0）或 --- a/src/…（strip=1）；hunk **带 2～3 行上下文**；**小步**单主题；可 **patch -R** / **git checkout** 回滚。先 dry-run。",
            category: ToolCategory::Development,
            parameters: tool_params::params_apply_patch,
            runner: runner_apply_patch,
            summary: ToolSummaryKind::Dynamic(ts::summary_apply_patch),
        },
        ToolSpec {
            name: "search_in_files",
            description: "在当前工作区内搜索文件内容。支持正则或关键词搜索，返回匹配的文件路径、行号和行片段。支持 context_before/context_after 上下文行、file_glob 文件名过滤、exclude_glob 排除。",
            category: ToolCategory::Development,
            parameters: tool_params::params_search_in_files_enhanced,
            runner: runner_search_in_files,
            summary: ToolSummaryKind::Dynamic(ts::summary_search_in_files),
        },
        ToolSpec {
            name: "codebase_semantic_search",
            description: "工作区内**语义**代码检索（本地 fastembed 向量 + SQLite 索引，与长期记忆分库）。首次或大改后请先 `rebuild_index: true` 建索引，再用 `query` 按自然语言找相近代码块（路径+行号+片段）。尊重 .gitignore；单文件大小与索引文件数受配置限制。精确字符串匹配仍优先用 search_in_files。",
            category: ToolCategory::Development,
            parameters: tool_params::params_codebase_semantic_search,
            runner: runner_codebase_semantic_search,
            summary: ToolSummaryKind::Dynamic(ts::summary_codebase_semantic_search),
        },
]
