[
ToolSpec {
            name: "git_stage_files",
            description: "将指定相对路径加入暂存区（受控写入）。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_stage_files,
            runner: runner_git_stage_files,
            summary: ToolSummaryKind::Static("暂存文件"),
        },
        ToolSpec {
            name: "git_commit",
            description: "执行 git commit（受控写入，需 confirm=true）。可选先 stage_all。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_commit,
            runner: runner_git_commit,
            summary: ToolSummaryKind::Static("提交变更"),
        },
        ToolSpec {
            name: "git_fetch",
            description: "执行 git fetch（可选 remote/branch/prune）。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_fetch,
            runner: runner_git_fetch,
            summary: ToolSummaryKind::Static("拉取远程更新"),
        },
        ToolSpec {
            name: "git_remote_list",
            description: "查看远程仓库列表（git remote -v）。",
            category: ToolCategory::Development,
            parameters: tool_params::params_empty_object,
            runner: runner_git_remote_list,
            summary: ToolSummaryKind::Static("查看远程仓库"),
        },
        ToolSpec {
            name: "git_remote_set_url",
            description: "设置远程仓库 URL（受控写入，需 confirm=true）。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_remote_set_url,
            runner: runner_git_remote_set_url,
            summary: ToolSummaryKind::Static("设置远程 URL"),
        },
        ToolSpec {
            name: "git_apply",
            description: "执行 git apply。默认 check_only=true 先检查可应用性。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_apply,
            runner: runner_git_apply,
            summary: ToolSummaryKind::Static("应用 Git 补丁"),
        },
        ToolSpec {
            name: "git_clone",
            description: "执行 git clone 到工作区内目标目录（受控写入，需 confirm=true）。",
            category: ToolCategory::Development,
            parameters: tool_params::params_git_clone,
            runner: runner_git_clone,
            summary: ToolSummaryKind::Static("克隆仓库"),
        },
]
