[
    ToolSpec {
        name: "gh_pr_list",
        description: "列出 GitHub Pull Request（封装 **`gh pr list`**）。可选 `owner/repo`、`state`、`limit`（默认 30，最大 200）、`fields`（`--json` 字段名）；若提供 `fields` 且命令成功，结果末尾附加**格式化 JSON** 便于模型解析。须本机已安装 **`gh`** 且配置 **`allowed_commands` 含 gh**；认证依赖环境（如 `gh auth login` / `GH_TOKEN`）。`extra_args` 须符合 run_command 安全规则（无 `..`、无 `/` 前缀）。",
        category: ToolCategory::Development,
        parameters: tool_params::params_gh_pr_list,
        runner: runner_gh_pr_list,
        summary: ToolSummaryKind::Dynamic(ts::summary_gh_pr_list),
    },
    ToolSpec {
        name: "gh_pr_view",
        description: "查看指定 PR（封装 **`gh pr view`**）。必填 `number`；可选 `repo`、`fields`（`--json`）、`web`、`extra_args`。提供 `fields` 时成功输出含格式化 JSON。",
        category: ToolCategory::Development,
        parameters: tool_params::params_gh_pr_view,
        runner: runner_gh_pr_view,
        summary: ToolSummaryKind::Dynamic(ts::summary_gh_pr_view),
    },
    ToolSpec {
        name: "gh_issue_list",
        description: "列出 Issue（封装 **`gh issue list`**）。可选 `repo`、`state`（open/closed/all）、`limit`、`fields`、`web`、`extra_args`。",
        category: ToolCategory::Development,
        parameters: tool_params::params_gh_issue_list,
        runner: runner_gh_issue_list,
        summary: ToolSummaryKind::Dynamic(ts::summary_gh_issue_list),
    },
    ToolSpec {
        name: "gh_issue_view",
        description: "查看指定 Issue（封装 **`gh issue view`**）。必填 `number`；可选 `repo`、`fields`、`web`、`extra_args`。",
        category: ToolCategory::Development,
        parameters: tool_params::params_gh_issue_view,
        runner: runner_gh_issue_view,
        summary: ToolSummaryKind::Dynamic(ts::summary_gh_issue_view),
    },
    ToolSpec {
        name: "gh_run_list",
        description: "列出 GitHub Actions 工作流运行（封装 **`gh run list`**）。可选 `repo`、`limit`、`fields`、`web`、`extra_args`。",
        category: ToolCategory::Development,
        parameters: tool_params::params_gh_run_list,
        runner: runner_gh_run_list,
        summary: ToolSummaryKind::Dynamic(ts::summary_gh_run_list),
    },
    ToolSpec {
        name: "gh_api",
        description: "调用 **`gh api`**（受限）：`path` 为**无前导 /** 的相对路径（如 `repos/owner/repo/pulls`）；`method` 默认 GET，支持 HEAD/POST/PATCH/PUT/DELETE；可选 JSON `body`（经 stdin 传入）。**写操作**（POST 等）可能修改远端资源，属非只读工具。`path` 字符集受限以降低注入面；勿在 body 中放入密钥。",
        category: ToolCategory::Development,
        parameters: tool_params::params_gh_api,
        runner: runner_gh_api,
        summary: ToolSummaryKind::Dynamic(ts::summary_gh_api),
    },
]
